# 5.9.0

VER=5

GH_MAJOR_VERSION=$${VER}
GH_MINOR_VERSION=9
GH_PATCH_VERSION=0

VERSION=$${GH_MAJOR_VERSION}.$${GH_MINOR_VERSION}.$${GH_PATCH_VERSION}

contains( CONFIG, __debug ) {
	message( VERSION set to $${VERSION} )
}
